# Generated by Django 4.2.2 on 2023-06-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
